// Code generated by MockGen. DO NOT EDIT.
// Source: storage_interface.go
//
// Generated by this command:
//
//	mockgen -typed -source storage_interface.go -destination storage_interface_mock.go -package=telegram_service
//

// Package telegram_service is a generated GoMock package.
package telegram_service

import (
	reflect "reflect"
	storage "telegramservice/internal/storage"

	gomock "go.uber.org/mock/gomock"
)

// MockStorageInterface is a mock of StorageInterface interface.
type MockStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockStorageInterfaceMockRecorder is the mock recorder for MockStorageInterface.
type MockStorageInterfaceMockRecorder struct {
	mock *MockStorageInterface
}

// NewMockStorageInterface creates a new mock instance.
func NewMockStorageInterface(ctrl *gomock.Controller) *MockStorageInterface {
	mock := &MockStorageInterface{ctrl: ctrl}
	mock.recorder = &MockStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageInterface) EXPECT() *MockStorageInterfaceMockRecorder {
	return m.recorder
}

// AddMessage mocks base method.
func (m *MockStorageInterface) AddMessage(msg *storage.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddMessage", msg)
}

// AddMessage indicates an expected call of AddMessage.
func (mr *MockStorageInterfaceMockRecorder) AddMessage(msg any) *MockStorageInterfaceAddMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessage", reflect.TypeOf((*MockStorageInterface)(nil).AddMessage), msg)
	return &MockStorageInterfaceAddMessageCall{Call: call}
}

// MockStorageInterfaceAddMessageCall wrap *gomock.Call
type MockStorageInterfaceAddMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageInterfaceAddMessageCall) Return() *MockStorageInterfaceAddMessageCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageInterfaceAddMessageCall) Do(f func(*storage.Message)) *MockStorageInterfaceAddMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageInterfaceAddMessageCall) DoAndReturn(f func(*storage.Message)) *MockStorageInterfaceAddMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteConnection mocks base method.
func (m *MockStorageInterface) DeleteConnection(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteConnection", id)
}

// DeleteConnection indicates an expected call of DeleteConnection.
func (mr *MockStorageInterfaceMockRecorder) DeleteConnection(id any) *MockStorageInterfaceDeleteConnectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnection", reflect.TypeOf((*MockStorageInterface)(nil).DeleteConnection), id)
	return &MockStorageInterfaceDeleteConnectionCall{Call: call}
}

// MockStorageInterfaceDeleteConnectionCall wrap *gomock.Call
type MockStorageInterfaceDeleteConnectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageInterfaceDeleteConnectionCall) Return() *MockStorageInterfaceDeleteConnectionCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageInterfaceDeleteConnectionCall) Do(f func(string)) *MockStorageInterfaceDeleteConnectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageInterfaceDeleteConnectionCall) DoAndReturn(f func(string)) *MockStorageInterfaceDeleteConnectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetConnection mocks base method.
func (m *MockStorageInterface) GetConnection(id string) (*storage.ConnectionInfo, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", id)
	ret0, _ := ret[0].(*storage.ConnectionInfo)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockStorageInterfaceMockRecorder) GetConnection(id any) *MockStorageInterfaceGetConnectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockStorageInterface)(nil).GetConnection), id)
	return &MockStorageInterfaceGetConnectionCall{Call: call}
}

// MockStorageInterfaceGetConnectionCall wrap *gomock.Call
type MockStorageInterfaceGetConnectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageInterfaceGetConnectionCall) Return(arg0 *storage.ConnectionInfo, arg1 bool) *MockStorageInterfaceGetConnectionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageInterfaceGetConnectionCall) Do(f func(string) (*storage.ConnectionInfo, bool)) *MockStorageInterfaceGetConnectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageInterfaceGetConnectionCall) DoAndReturn(f func(string) (*storage.ConnectionInfo, bool)) *MockStorageInterfaceGetConnectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMessages mocks base method.
func (m *MockStorageInterface) GetMessages(connectionID string, limit int) []*storage.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessages", connectionID, limit)
	ret0, _ := ret[0].([]*storage.Message)
	return ret0
}

// GetMessages indicates an expected call of GetMessages.
func (mr *MockStorageInterfaceMockRecorder) GetMessages(connectionID, limit any) *MockStorageInterfaceGetMessagesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessages", reflect.TypeOf((*MockStorageInterface)(nil).GetMessages), connectionID, limit)
	return &MockStorageInterfaceGetMessagesCall{Call: call}
}

// MockStorageInterfaceGetMessagesCall wrap *gomock.Call
type MockStorageInterfaceGetMessagesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageInterfaceGetMessagesCall) Return(arg0 []*storage.Message) *MockStorageInterfaceGetMessagesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageInterfaceGetMessagesCall) Do(f func(string, int) []*storage.Message) *MockStorageInterfaceGetMessagesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageInterfaceGetMessagesCall) DoAndReturn(f func(string, int) []*storage.Message) *MockStorageInterfaceGetMessagesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListConnections mocks base method.
func (m *MockStorageInterface) ListConnections() []*storage.ConnectionInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnections")
	ret0, _ := ret[0].([]*storage.ConnectionInfo)
	return ret0
}

// ListConnections indicates an expected call of ListConnections.
func (mr *MockStorageInterfaceMockRecorder) ListConnections() *MockStorageInterfaceListConnectionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnections", reflect.TypeOf((*MockStorageInterface)(nil).ListConnections))
	return &MockStorageInterfaceListConnectionsCall{Call: call}
}

// MockStorageInterfaceListConnectionsCall wrap *gomock.Call
type MockStorageInterfaceListConnectionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageInterfaceListConnectionsCall) Return(arg0 []*storage.ConnectionInfo) *MockStorageInterfaceListConnectionsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageInterfaceListConnectionsCall) Do(f func() []*storage.ConnectionInfo) *MockStorageInterfaceListConnectionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageInterfaceListConnectionsCall) DoAndReturn(f func() []*storage.ConnectionInfo) *MockStorageInterfaceListConnectionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveConnection mocks base method.
func (m *MockStorageInterface) SaveConnection(conn *storage.ConnectionInfo) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveConnection", conn)
}

// SaveConnection indicates an expected call of SaveConnection.
func (mr *MockStorageInterfaceMockRecorder) SaveConnection(conn any) *MockStorageInterfaceSaveConnectionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveConnection", reflect.TypeOf((*MockStorageInterface)(nil).SaveConnection), conn)
	return &MockStorageInterfaceSaveConnectionCall{Call: call}
}

// MockStorageInterfaceSaveConnectionCall wrap *gomock.Call
type MockStorageInterfaceSaveConnectionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageInterfaceSaveConnectionCall) Return() *MockStorageInterfaceSaveConnectionCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageInterfaceSaveConnectionCall) Do(f func(*storage.ConnectionInfo)) *MockStorageInterfaceSaveConnectionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageInterfaceSaveConnectionCall) DoAndReturn(f func(*storage.ConnectionInfo)) *MockStorageInterfaceSaveConnectionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateConnectionStatus mocks base method.
func (m *MockStorageInterface) UpdateConnectionStatus(id, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateConnectionStatus", id, status)
}

// UpdateConnectionStatus indicates an expected call of UpdateConnectionStatus.
func (mr *MockStorageInterfaceMockRecorder) UpdateConnectionStatus(id, status any) *MockStorageInterfaceUpdateConnectionStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnectionStatus", reflect.TypeOf((*MockStorageInterface)(nil).UpdateConnectionStatus), id, status)
	return &MockStorageInterfaceUpdateConnectionStatusCall{Call: call}
}

// MockStorageInterfaceUpdateConnectionStatusCall wrap *gomock.Call
type MockStorageInterfaceUpdateConnectionStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageInterfaceUpdateConnectionStatusCall) Return() *MockStorageInterfaceUpdateConnectionStatusCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageInterfaceUpdateConnectionStatusCall) Do(f func(string, string)) *MockStorageInterfaceUpdateConnectionStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageInterfaceUpdateConnectionStatusCall) DoAndReturn(f func(string, string)) *MockStorageInterfaceUpdateConnectionStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
