// Code generated by MockGen. DO NOT EDIT.
// Source: telegram_interface.go
//
// Generated by this command:
//
//	mockgen -typed -source telegram_interface.go -destination telegram_interface_mock.go -package=telegram_service
//

// Package telegram_service is a generated GoMock package.
package telegram_service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTelegramClientInterface is a mock of TelegramClientInterface interface.
type MockTelegramClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramClientInterfaceMockRecorder
	isgomock struct{}
}

// MockTelegramClientInterfaceMockRecorder is the mock recorder for MockTelegramClientInterface.
type MockTelegramClientInterfaceMockRecorder struct {
	mock *MockTelegramClientInterface
}

// NewMockTelegramClientInterface creates a new mock instance.
func NewMockTelegramClientInterface(ctrl *gomock.Controller) *MockTelegramClientInterface {
	mock := &MockTelegramClientInterface{ctrl: ctrl}
	mock.recorder = &MockTelegramClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramClientInterface) EXPECT() *MockTelegramClientInterfaceMockRecorder {
	return m.recorder
}

// IsAuthorized mocks base method.
func (m *MockTelegramClientInterface) IsAuthorized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAuthorized indicates an expected call of IsAuthorized.
func (mr *MockTelegramClientInterfaceMockRecorder) IsAuthorized() *MockTelegramClientInterfaceIsAuthorizedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorized", reflect.TypeOf((*MockTelegramClientInterface)(nil).IsAuthorized))
	return &MockTelegramClientInterfaceIsAuthorizedCall{Call: call}
}

// MockTelegramClientInterfaceIsAuthorizedCall wrap *gomock.Call
type MockTelegramClientInterfaceIsAuthorizedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceIsAuthorizedCall) Return(arg0 bool) *MockTelegramClientInterfaceIsAuthorizedCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceIsAuthorizedCall) Do(f func() bool) *MockTelegramClientInterfaceIsAuthorizedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceIsAuthorizedCall) DoAndReturn(f func() bool) *MockTelegramClientInterfaceIsAuthorizedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendMessage mocks base method.
func (m *MockTelegramClientInterface) SendMessage(ctx context.Context, chatID, text string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, chatID, text)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockTelegramClientInterfaceMockRecorder) SendMessage(ctx, chatID, text any) *MockTelegramClientInterfaceSendMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockTelegramClientInterface)(nil).SendMessage), ctx, chatID, text)
	return &MockTelegramClientInterfaceSendMessageCall{Call: call}
}

// MockTelegramClientInterfaceSendMessageCall wrap *gomock.Call
type MockTelegramClientInterfaceSendMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceSendMessageCall) Return(arg0 string, arg1 error) *MockTelegramClientInterfaceSendMessageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceSendMessageCall) Do(f func(context.Context, string, string) (string, error)) *MockTelegramClientInterfaceSendMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceSendMessageCall) DoAndReturn(f func(context.Context, string, string) (string, error)) *MockTelegramClientInterfaceSendMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Start mocks base method.
func (m *MockTelegramClientInterface) Start(ctx context.Context, qrCodeReady func(string)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, qrCodeReady)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockTelegramClientInterfaceMockRecorder) Start(ctx, qrCodeReady any) *MockTelegramClientInterfaceStartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTelegramClientInterface)(nil).Start), ctx, qrCodeReady)
	return &MockTelegramClientInterfaceStartCall{Call: call}
}

// MockTelegramClientInterfaceStartCall wrap *gomock.Call
type MockTelegramClientInterfaceStartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceStartCall) Return(arg0 error) *MockTelegramClientInterfaceStartCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceStartCall) Do(f func(context.Context, func(string)) error) *MockTelegramClientInterfaceStartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceStartCall) DoAndReturn(f func(context.Context, func(string)) error) *MockTelegramClientInterfaceStartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stop mocks base method.
func (m *MockTelegramClientInterface) Stop(ctx context.Context, logout bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, logout)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockTelegramClientInterfaceMockRecorder) Stop(ctx, logout any) *MockTelegramClientInterfaceStopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTelegramClientInterface)(nil).Stop), ctx, logout)
	return &MockTelegramClientInterfaceStopCall{Call: call}
}

// MockTelegramClientInterfaceStopCall wrap *gomock.Call
type MockTelegramClientInterfaceStopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceStopCall) Return(arg0 error) *MockTelegramClientInterfaceStopCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceStopCall) Do(f func(context.Context, bool) error) *MockTelegramClientInterfaceStopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceStopCall) DoAndReturn(f func(context.Context, bool) error) *MockTelegramClientInterfaceStopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
