// Code generated by MockGen. DO NOT EDIT.
// Source: telegram_client_interface.go
//
// Generated by this command:
//
//	mockgen -typed -source telegram_client_interface.go -destination telegram_client_interface_mock.go -package=telegram_client
//

// Package telegram_client is a generated GoMock package.
package telegram_client

import (
	context "context"
	reflect "reflect"

	auth "github.com/gotd/td/telegram/auth"
	qrlogin "github.com/gotd/td/telegram/auth/qrlogin"
	tg "github.com/gotd/td/tg"
	gomock "go.uber.org/mock/gomock"
)

// MockTelegramClientInterface is a mock of TelegramClientInterface interface.
type MockTelegramClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTelegramClientInterfaceMockRecorder
	isgomock struct{}
}

// MockTelegramClientInterfaceMockRecorder is the mock recorder for MockTelegramClientInterface.
type MockTelegramClientInterfaceMockRecorder struct {
	mock *MockTelegramClientInterface
}

// NewMockTelegramClientInterface creates a new mock instance.
func NewMockTelegramClientInterface(ctrl *gomock.Controller) *MockTelegramClientInterface {
	mock := &MockTelegramClientInterface{ctrl: ctrl}
	mock.recorder = &MockTelegramClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTelegramClientInterface) EXPECT() *MockTelegramClientInterfaceMockRecorder {
	return m.recorder
}

// API mocks base method.
func (m *MockTelegramClientInterface) API() TGClientInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "API")
	ret0, _ := ret[0].(TGClientInterface)
	return ret0
}

// API indicates an expected call of API.
func (mr *MockTelegramClientInterfaceMockRecorder) API() *MockTelegramClientInterfaceAPICall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "API", reflect.TypeOf((*MockTelegramClientInterface)(nil).API))
	return &MockTelegramClientInterfaceAPICall{Call: call}
}

// MockTelegramClientInterfaceAPICall wrap *gomock.Call
type MockTelegramClientInterfaceAPICall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceAPICall) Return(arg0 TGClientInterface) *MockTelegramClientInterfaceAPICall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceAPICall) Do(f func() TGClientInterface) *MockTelegramClientInterfaceAPICall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceAPICall) DoAndReturn(f func() TGClientInterface) *MockTelegramClientInterfaceAPICall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Auth mocks base method.
func (m *MockTelegramClientInterface) Auth() AuthClientInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth")
	ret0, _ := ret[0].(AuthClientInterface)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockTelegramClientInterfaceMockRecorder) Auth() *MockTelegramClientInterfaceAuthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockTelegramClientInterface)(nil).Auth))
	return &MockTelegramClientInterfaceAuthCall{Call: call}
}

// MockTelegramClientInterfaceAuthCall wrap *gomock.Call
type MockTelegramClientInterfaceAuthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceAuthCall) Return(arg0 AuthClientInterface) *MockTelegramClientInterfaceAuthCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceAuthCall) Do(f func() AuthClientInterface) *MockTelegramClientInterfaceAuthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceAuthCall) DoAndReturn(f func() AuthClientInterface) *MockTelegramClientInterfaceAuthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QR mocks base method.
func (m *MockTelegramClientInterface) QR() QRClientInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QR")
	ret0, _ := ret[0].(QRClientInterface)
	return ret0
}

// QR indicates an expected call of QR.
func (mr *MockTelegramClientInterfaceMockRecorder) QR() *MockTelegramClientInterfaceQRCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QR", reflect.TypeOf((*MockTelegramClientInterface)(nil).QR))
	return &MockTelegramClientInterfaceQRCall{Call: call}
}

// MockTelegramClientInterfaceQRCall wrap *gomock.Call
type MockTelegramClientInterfaceQRCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceQRCall) Return(arg0 QRClientInterface) *MockTelegramClientInterfaceQRCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceQRCall) Do(f func() QRClientInterface) *MockTelegramClientInterfaceQRCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceQRCall) DoAndReturn(f func() QRClientInterface) *MockTelegramClientInterfaceQRCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Run mocks base method.
func (m *MockTelegramClientInterface) Run(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTelegramClientInterfaceMockRecorder) Run(ctx, f any) *MockTelegramClientInterfaceRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTelegramClientInterface)(nil).Run), ctx, f)
	return &MockTelegramClientInterfaceRunCall{Call: call}
}

// MockTelegramClientInterfaceRunCall wrap *gomock.Call
type MockTelegramClientInterfaceRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTelegramClientInterfaceRunCall) Return(err error) *MockTelegramClientInterfaceRunCall {
	c.Call = c.Call.Return(err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTelegramClientInterfaceRunCall) Do(f func(context.Context, func(context.Context) error) error) *MockTelegramClientInterfaceRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTelegramClientInterfaceRunCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MockTelegramClientInterfaceRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTGClientInterface is a mock of TGClientInterface interface.
type MockTGClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTGClientInterfaceMockRecorder
	isgomock struct{}
}

// MockTGClientInterfaceMockRecorder is the mock recorder for MockTGClientInterface.
type MockTGClientInterfaceMockRecorder struct {
	mock *MockTGClientInterface
}

// NewMockTGClientInterface creates a new mock instance.
func NewMockTGClientInterface(ctrl *gomock.Controller) *MockTGClientInterface {
	mock := &MockTGClientInterface{ctrl: ctrl}
	mock.recorder = &MockTGClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTGClientInterface) EXPECT() *MockTGClientInterfaceMockRecorder {
	return m.recorder
}

// ContactsResolveUsername mocks base method.
func (m *MockTGClientInterface) ContactsResolveUsername(ctx context.Context, request *tg.ContactsResolveUsernameRequest) (*tg.ContactsResolvedPeer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContactsResolveUsername", ctx, request)
	ret0, _ := ret[0].(*tg.ContactsResolvedPeer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContactsResolveUsername indicates an expected call of ContactsResolveUsername.
func (mr *MockTGClientInterfaceMockRecorder) ContactsResolveUsername(ctx, request any) *MockTGClientInterfaceContactsResolveUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContactsResolveUsername", reflect.TypeOf((*MockTGClientInterface)(nil).ContactsResolveUsername), ctx, request)
	return &MockTGClientInterfaceContactsResolveUsernameCall{Call: call}
}

// MockTGClientInterfaceContactsResolveUsernameCall wrap *gomock.Call
type MockTGClientInterfaceContactsResolveUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTGClientInterfaceContactsResolveUsernameCall) Return(arg0 *tg.ContactsResolvedPeer, arg1 error) *MockTGClientInterfaceContactsResolveUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTGClientInterfaceContactsResolveUsernameCall) Do(f func(context.Context, *tg.ContactsResolveUsernameRequest) (*tg.ContactsResolvedPeer, error)) *MockTGClientInterfaceContactsResolveUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTGClientInterfaceContactsResolveUsernameCall) DoAndReturn(f func(context.Context, *tg.ContactsResolveUsernameRequest) (*tg.ContactsResolvedPeer, error)) *MockTGClientInterfaceContactsResolveUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Raw mocks base method.
func (m *MockTGClientInterface) Raw() *tg.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Raw")
	ret0, _ := ret[0].(*tg.Client)
	return ret0
}

// Raw indicates an expected call of Raw.
func (mr *MockTGClientInterfaceMockRecorder) Raw() *MockTGClientInterfaceRawCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Raw", reflect.TypeOf((*MockTGClientInterface)(nil).Raw))
	return &MockTGClientInterfaceRawCall{Call: call}
}

// MockTGClientInterfaceRawCall wrap *gomock.Call
type MockTGClientInterfaceRawCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTGClientInterfaceRawCall) Return(arg0 *tg.Client) *MockTGClientInterfaceRawCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTGClientInterfaceRawCall) Do(f func() *tg.Client) *MockTGClientInterfaceRawCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTGClientInterfaceRawCall) DoAndReturn(f func() *tg.Client) *MockTGClientInterfaceRawCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAuthClientInterface is a mock of AuthClientInterface interface.
type MockAuthClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthClientInterfaceMockRecorder is the mock recorder for MockAuthClientInterface.
type MockAuthClientInterfaceMockRecorder struct {
	mock *MockAuthClientInterface
}

// NewMockAuthClientInterface creates a new mock instance.
func NewMockAuthClientInterface(ctrl *gomock.Controller) *MockAuthClientInterface {
	mock := &MockAuthClientInterface{ctrl: ctrl}
	mock.recorder = &MockAuthClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthClientInterface) EXPECT() *MockAuthClientInterfaceMockRecorder {
	return m.recorder
}

// Status mocks base method.
func (m *MockAuthClientInterface) Status(ctx context.Context) (*auth.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(*auth.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockAuthClientInterfaceMockRecorder) Status(ctx any) *MockAuthClientInterfaceStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockAuthClientInterface)(nil).Status), ctx)
	return &MockAuthClientInterfaceStatusCall{Call: call}
}

// MockAuthClientInterfaceStatusCall wrap *gomock.Call
type MockAuthClientInterfaceStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthClientInterfaceStatusCall) Return(arg0 *auth.Status, arg1 error) *MockAuthClientInterfaceStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthClientInterfaceStatusCall) Do(f func(context.Context) (*auth.Status, error)) *MockAuthClientInterfaceStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthClientInterfaceStatusCall) DoAndReturn(f func(context.Context) (*auth.Status, error)) *MockAuthClientInterfaceStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockQRClientInterface is a mock of QRClientInterface interface.
type MockQRClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockQRClientInterfaceMockRecorder
	isgomock struct{}
}

// MockQRClientInterfaceMockRecorder is the mock recorder for MockQRClientInterface.
type MockQRClientInterfaceMockRecorder struct {
	mock *MockQRClientInterface
}

// NewMockQRClientInterface creates a new mock instance.
func NewMockQRClientInterface(ctrl *gomock.Controller) *MockQRClientInterface {
	mock := &MockQRClientInterface{ctrl: ctrl}
	mock.recorder = &MockQRClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQRClientInterface) EXPECT() *MockQRClientInterfaceMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockQRClientInterface) Auth(ctx context.Context, loggedIn qrlogin.LoggedIn, show func(context.Context, qrlogin.Token) error, exceptIDs ...int64) (*tg.AuthAuthorization, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, loggedIn, show}
	for _, a := range exceptIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Auth", varargs...)
	ret0, _ := ret[0].(*tg.AuthAuthorization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockQRClientInterfaceMockRecorder) Auth(ctx, loggedIn, show any, exceptIDs ...any) *MockQRClientInterfaceAuthCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, loggedIn, show}, exceptIDs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockQRClientInterface)(nil).Auth), varargs...)
	return &MockQRClientInterfaceAuthCall{Call: call}
}

// MockQRClientInterfaceAuthCall wrap *gomock.Call
type MockQRClientInterfaceAuthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockQRClientInterfaceAuthCall) Return(arg0 *tg.AuthAuthorization, arg1 error) *MockQRClientInterfaceAuthCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockQRClientInterfaceAuthCall) Do(f func(context.Context, qrlogin.LoggedIn, func(context.Context, qrlogin.Token) error, ...int64) (*tg.AuthAuthorization, error)) *MockQRClientInterfaceAuthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockQRClientInterfaceAuthCall) DoAndReturn(f func(context.Context, qrlogin.LoggedIn, func(context.Context, qrlogin.Token) error, ...int64) (*tg.AuthAuthorization, error)) *MockQRClientInterfaceAuthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
